version: "3"

services:
  converter:
    hostname: converter
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 768M
    logging:
      driver: "local"
      options:
        max-size: "50m"
    build:
      context: .
      dockerfile: ./docker/converter.Dockerfile
    restart: always
    user: "65532:65532"
    volumes:
      - .:/w:rw
    working_dir: "/w"

  app:
    hostname: app
    depends_on:
      converter:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    logging:
      driver: "local"
      options:
        max-size: "50m"
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    restart: always
    volumes:
      # https://github.com/GoogleContainerTools/distroless/issues/427#issuecomment-547874186
      # mkdir data; chown 65532:65532 data
      - .:/home/nonroot/suno-radio:rw
    working_dir: "/home/nonroot/suno-radio"

  pub:
    depends_on:
      app:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
    logging:
      driver: "local"
      options:
        max-size: "10m"
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate --loglevel info --transport-loglevel fatal --quick-service http://app:7890 --url http://app:3000 --protocol http2
